[project]
name = "doh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hpack>=4.0.0",
    "numpy>=2.2.1",
    "pyshark>=0.6",
    "scipy>=1.15.1",
]
